"""T+1 soft-adaptive medium/short-term trend strategy, version 1.3.x.

Phase 1 exposes OpportunityScore. Phase 2 adds independent pure calculators
for market, divergence, risk, and execution overlays without depending on the
legacy thermostat implementation.
"""

from stock_picker.strategies.adaptive_trend_v1_3.divergence import (
    calculate_divergence,
    calculate_macd,
    find_swing_points,
)
from stock_picker.strategies.adaptive_trend_v1_3.execution_gate import (
    REQUIRED_BAR_STARTS,
    calculate_emergency_market_gate,
    calculate_execution_gate,
)
from stock_picker.strategies.adaptive_trend_v1_3.fill_engine import (
    calculate_fill_fees,
    execute_fill,
)
from stock_picker.strategies.adaptive_trend_v1_3.market_overlay import (
    MARKET_INDEX_WEIGHTS,
    calculate_market_overlay,
    effective_exposure_cap,
    score_index_factors,
    wilder_atr,
)
from stock_picker.strategies.adaptive_trend_v1_3.minute_contract import (
    LEGAL_BAR_START_TIMES,
    SHANGHAI_TIMEZONE,
    legal_bar_start_times,
    normalize_security_symbol,
    resolve_next_execution_bar,
    validate_minute_bars,
    validate_target_minute_bars,
)

from stock_picker.strategies.adaptive_trend_v1_3.opportunity_score import (
    BENCHMARK_WEIGHTS,
    MIN_HISTORY_DAYS,
    OPPORTUNITY_OUTPUT_COLUMNS,
    OpportunityInputError,
    OpportunityStatus,
    abs_rs,
    calculate_opportunity_scores,
    calculate_weighted_benchmark_returns,
    clip01,
    score_close_ma20,
    score_ma20_ma60,
    score_ma60_slope,
    score_signed_er,
    score_signed_er_change,
    signed_er_series,
)
from stock_picker.strategies.adaptive_trend_v1_3.phase2_models import (
    DivergenceSignal,
    DivergenceSnapshot,
    DivergenceStrength,
    DivergenceType,
    EmergencyIndexInput,
    EmergencyMarketResult,
    EmergencyStatus,
    ExecutionGateResult,
    ExecutionGateStatus,
    ExecutionStatus,
    HoldingRiskAction,
    Phase2Status,
    RiskOverlayResult,
    RiskStatus,
    SecurityStatus,
)
from stock_picker.strategies.adaptive_trend_v1_3.phase3_models import (
    ExecutionBarResolution,
    ExecutionType,
    FeeRuleSnapshot,
    FillRequest,
    FillResult,
    FillSide,
    FillStatus,
    MinuteContractResult,
    TradingRuleSnapshot,
)
from stock_picker.strategies.adaptive_trend_v1_3.phase4_models import (
    CandidateInput,
    ClassificationMetadata,
    ExistingHolding,
    IndustryClassificationSnapshot,
    Phase4Status,
    PortfolioAllocationResult,
    PositionLot,
    PositionState,
    PositionStatus,
    PositionTransitionResult,
    SizingResult,
    T1RiskObservation,
    T1RiskResult,
    TransitionStatus,
)
from stock_picker.strategies.adaptive_trend_v1_3.portfolio_allocator import (
    allocate_portfolio,
)
from stock_picker.strategies.adaptive_trend_v1_3.position_sizing import (
    calculate_candidate_sizing,
    correlation_multiplier_for_candidate,
    normal_and_effective_risk,
    order_quantity,
    pearson_correlation,
    raw_weight_from_risk,
)
from stock_picker.strategies.adaptive_trend_v1_3.position_state import (
    apply_buy_fill,
    apply_sell_fill,
    empty_position_state,
    unlock_position_state,
)
from stock_picker.strategies.adaptive_trend_v1_3.risk_overlay import (
    calculate_risk_overlay,
)
from stock_picker.strategies.adaptive_trend_v1_3.t1_tail_risk import (
    build_t1_risk_observation,
    calculate_t1_risk,
    linear_quantile_95,
)

__all__ = [
    "BENCHMARK_WEIGHTS",
    "CandidateInput",
    "ClassificationMetadata",
    "DivergenceSignal",
    "DivergenceSnapshot",
    "DivergenceStrength",
    "DivergenceType",
    "EmergencyIndexInput",
    "EmergencyMarketResult",
    "EmergencyStatus",
    "ExecutionBarResolution",
    "ExecutionGateResult",
    "ExecutionGateStatus",
    "ExecutionStatus",
    "ExecutionType",
    "ExistingHolding",
    "IndustryClassificationSnapshot",
    "FeeRuleSnapshot",
    "FillRequest",
    "FillResult",
    "FillSide",
    "FillStatus",
    "HoldingRiskAction",
    "LEGAL_BAR_START_TIMES",
    "MARKET_INDEX_WEIGHTS",
    "MIN_HISTORY_DAYS",
    "MinuteContractResult",
    "OPPORTUNITY_OUTPUT_COLUMNS",
    "OpportunityInputError",
    "OpportunityStatus",
    "Phase4Status",
    "Phase2Status",
    "REQUIRED_BAR_STARTS",
    "RiskOverlayResult",
    "RiskStatus",
    "PortfolioAllocationResult",
    "PositionLot",
    "PositionState",
    "PositionStatus",
    "PositionTransitionResult",
    "SHANGHAI_TIMEZONE",
    "SecurityStatus",
    "TradingRuleSnapshot",
    "SizingResult",
    "T1RiskObservation",
    "T1RiskResult",
    "TransitionStatus",
    "abs_rs",
    "calculate_opportunity_scores",
    "calculate_candidate_sizing",
    "calculate_divergence",
    "calculate_emergency_market_gate",
    "calculate_execution_gate",
    "calculate_fill_fees",
    "calculate_macd",
    "calculate_market_overlay",
    "calculate_risk_overlay",
    "calculate_t1_risk",
    "calculate_weighted_benchmark_returns",
    "clip01",
    "effective_exposure_cap",
    "empty_position_state",
    "execute_fill",
    "allocate_portfolio",
    "apply_buy_fill",
    "apply_sell_fill",
    "build_t1_risk_observation",
    "correlation_multiplier_for_candidate",
    "find_swing_points",
    "legal_bar_start_times",
    "linear_quantile_95",
    "normal_and_effective_risk",
    "normalize_security_symbol",
    "resolve_next_execution_bar",
    "order_quantity",
    "pearson_correlation",
    "raw_weight_from_risk",
    "score_close_ma20",
    "score_ma20_ma60",
    "score_ma60_slope",
    "score_signed_er",
    "score_signed_er_change",
    "score_index_factors",
    "signed_er_series",
    "validate_minute_bars",
    "validate_target_minute_bars",
    "unlock_position_state",
    "wilder_atr",
]
