"""T+1 soft-adaptive medium/short-term trend strategy, version 1.3.x.

Phase 1 exposes OpportunityScore. Phase 2 adds independent pure calculators
for market, divergence, risk, and execution overlays without depending on the
legacy thermostat implementation.
"""

from stock_picker.strategies.adaptive_trend_v1_3.divergence import (
    calculate_divergence,
    calculate_macd,
    find_swing_points,
)
from stock_picker.strategies.adaptive_trend_v1_3.execution_gate import (
    REQUIRED_BAR_STARTS,
    calculate_emergency_market_gate,
    calculate_execution_gate,
)
from stock_picker.strategies.adaptive_trend_v1_3.fill_engine import (
    calculate_fill_fees,
    execute_fill,
)
from stock_picker.strategies.adaptive_trend_v1_3.market_overlay import (
    MARKET_INDEX_WEIGHTS,
    calculate_market_overlay,
    effective_exposure_cap,
    score_index_factors,
    wilder_atr,
)
from stock_picker.strategies.adaptive_trend_v1_3.minute_contract import (
    LEGAL_BAR_START_TIMES,
    SHANGHAI_TIMEZONE,
    legal_bar_start_times,
    normalize_security_symbol,
    resolve_next_execution_bar,
    validate_minute_bars,
    validate_target_minute_bars,
)

from stock_picker.strategies.adaptive_trend_v1_3.opportunity_score import (
    BENCHMARK_WEIGHTS,
    MIN_HISTORY_DAYS,
    OPPORTUNITY_OUTPUT_COLUMNS,
    OpportunityInputError,
    OpportunityStatus,
    abs_rs,
    calculate_opportunity_scores,
    calculate_weighted_benchmark_returns,
    clip01,
    score_close_ma20,
    score_ma20_ma60,
    score_ma60_slope,
    score_signed_er,
    score_signed_er_change,
    signed_er_series,
)
from stock_picker.strategies.adaptive_trend_v1_3.phase2_models import (
    DivergenceSignal,
    DivergenceSnapshot,
    DivergenceStrength,
    DivergenceType,
    EmergencyIndexInput,
    EmergencyMarketResult,
    EmergencyStatus,
    ExecutionGateResult,
    ExecutionGateStatus,
    ExecutionStatus,
    HoldingRiskAction,
    Phase2Status,
    RiskOverlayResult,
    RiskStatus,
    SecurityStatus,
)
from stock_picker.strategies.adaptive_trend_v1_3.phase3_models import (
    ExecutionBarResolution,
    ExecutionType,
    FeeRuleSnapshot,
    FillRequest,
    FillResult,
    FillSide,
    FillStatus,
    MinuteContractResult,
    TradingRuleSnapshot,
)
from stock_picker.strategies.adaptive_trend_v1_3.phase4_models import (
    CandidateInput,
    ClassificationMetadata,
    ExistingHolding,
    IndustryClassificationSnapshot,
    Phase4Status,
    PortfolioAllocationResult,
    PositionLot,
    PositionState,
    PositionStatus,
    PositionTransitionResult,
    SizingResult,
    T1RiskObservation,
    T1RiskResult,
    TransitionStatus,
)
from stock_picker.strategies.adaptive_trend_v1_3.portfolio_allocator import (
    allocate_portfolio,
)
from stock_picker.strategies.adaptive_trend_v1_3.position_sizing import (
    calculate_candidate_sizing,
    correlation_multiplier_for_candidate,
    normal_and_effective_risk,
    order_quantity,
    pearson_correlation,
    raw_weight_from_risk,
)
from stock_picker.strategies.adaptive_trend_v1_3.position_state import (
    apply_buy_fill,
    apply_sell_fill,
    empty_position_state,
    unlock_position_state,
)
from stock_picker.strategies.adaptive_trend_v1_3.risk_overlay import (
    calculate_risk_overlay,
)
from stock_picker.strategies.adaptive_trend_v1_3.t1_tail_risk import (
    build_t1_risk_observation,
    calculate_t1_risk,
    linear_quantile_95,
)
from stock_picker.strategies.adaptive_trend_v1_3.cooldown import (
    COOLDOWN_DAYS,
    cooldown_blocked,
    create_cooldown_record,
    merge_cooldown_records,
)
from stock_picker.strategies.adaptive_trend_v1_3.exit_coordinator import (
    coordinate_1430_exit_cycle,
)
from stock_picker.strategies.adaptive_trend_v1_3.exit_control_state import (
    in_soft_exit_protection,
    initialize_exit_control,
    mark_episode_acted,
    record_full_exit,
    update_trailing_stop,
)
from stock_picker.strategies.adaptive_trend_v1_3.exit_engine import (
    EXIT_PRIORITY,
    build_exit_fill_request,
    canonical_exit_priority,
    evaluate_1430_exit,
    evaluate_hard_exit,
    reduction_quantity,
    select_highest_intent,
)
from stock_picker.strategies.adaptive_trend_v1_3.pending_sell import (
    apply_pending_fill_result,
    create_or_merge_pending,
    initial_pending_attempt,
    next_pending_attempt,
    revalidate_pending,
)
from stock_picker.strategies.adaptive_trend_v1_3.phase4b_models import (
    AttemptIdentity,
    CooldownRecord,
    CooldownStatus,
    DeriskHoldingInput,
    ExitControlState,
    ExitCycleHoldingInput,
    ExitCycleResult,
    ExitDecisionResult,
    ExitDecisionStatus,
    ExitIntent,
    PendingSellState,
    PendingSellStatus,
    PendingUpdateResult,
    PortfolioDeriskResult,
    ReplacementCandidate,
    ReplacementIncumbent,
    ReplacementResult,
    StopUpdateResult,
)
from stock_picker.strategies.adaptive_trend_v1_3.portfolio_derisk import (
    plan_portfolio_derisk,
    select_replacement_exit,
)
from stock_picker.strategies.adaptive_trend_v1_3.account_ledger import (
    apply_fill_to_ledger,
    rebuild_cash,
)
from stock_picker.strategies.adaptive_trend_v1_3.account_snapshot_service import (
    create_account_snapshot,
)
from stock_picker.strategies.adaptive_trend_v1_3.data_catalog import (
    DataCatalog,
    LookaheadAccessError,
    MarketView,
)
from stock_picker.strategies.adaptive_trend_v1_3.data_snapshot import (
    create_data_snapshot,
    verify_data_snapshot,
)
from stock_picker.strategies.adaptive_trend_v1_3.date_range import (
    WARMUP_TRADING_DAYS,
    resolve_date_range,
)
from stock_picker.strategies.adaptive_trend_v1_3.event_clock import (
    build_event_clock,
    deterministic_id,
)
from stock_picker.strategies.adaptive_trend_v1_3.market_cache import (
    RAW_PRICE_BASIS,
    MarketCache,
    fetch_complete_partition,
    validate_coverage,
    validate_partition,
)
from stock_picker.strategies.adaptive_trend_v1_3.performance_metrics import (
    build_benchmark_curve,
    calculate_performance_metrics,
)
from stock_picker.strategies.adaptive_trend_v1_3.phase5_models import (
    AccountProfile,
    AccountSnapshot,
    CachePartition,
    ClockEvent,
    DataReadinessReport,
    DataSnapshot,
    DateRangeKind,
    DateRangeSpec,
    LedgerEvent,
    NetworkAccessPolicy,
    PartitionStatus,
    PerformanceMetrics,
    Phase5Error,
    ResolvedDateRange,
    ResolvedUniverse,
    RunConfig,
    RunMode,
    RunStatus,
    RunSummary,
    ServiceResult,
    UniverseKind,
    UniverseSnapshot,
    UniverseSpec,
)
from stock_picker.strategies.adaptive_trend_v1_3.phase5_service import (
    PartitionRequest,
    Phase5Service,
    prepare_market_cache,
    resolve_run_inputs,
    validate_data_readiness,
)
from stock_picker.strategies.adaptive_trend_v1_3.run_orchestrator import (
    CoreStrategyDependencies,
    RuntimeDataDependencies,
    RuntimeHooks,
    create_run,
    execute_run,
    run_fingerprint,
)
from stock_picker.strategies.adaptive_trend_v1_3.run_recovery import resume_run
from stock_picker.strategies.adaptive_trend_v1_3.run_reporting import (
    generate_run_report,
)
from stock_picker.strategies.adaptive_trend_v1_3.run_store import RunStore
from stock_picker.strategies.adaptive_trend_v1_3.valuation import (
    SessionCloseMark,
    select_session_close_mark,
)
from stock_picker.strategies.adaptive_trend_v1_3.universe_resolver import (
    BENCHMARK_SYMBOLS,
    resolve_universe,
)

__all__ = [
    "BENCHMARK_WEIGHTS",
    "CandidateInput",
    "ClassificationMetadata",
    "DivergenceSignal",
    "DivergenceSnapshot",
    "DivergenceStrength",
    "DivergenceType",
    "EmergencyIndexInput",
    "EmergencyMarketResult",
    "EmergencyStatus",
    "ExecutionBarResolution",
    "ExecutionGateResult",
    "ExecutionGateStatus",
    "ExecutionStatus",
    "ExecutionType",
    "ExistingHolding",
    "IndustryClassificationSnapshot",
    "FeeRuleSnapshot",
    "FillRequest",
    "FillResult",
    "FillSide",
    "FillStatus",
    "HoldingRiskAction",
    "LEGAL_BAR_START_TIMES",
    "MARKET_INDEX_WEIGHTS",
    "MIN_HISTORY_DAYS",
    "MinuteContractResult",
    "OPPORTUNITY_OUTPUT_COLUMNS",
    "OpportunityInputError",
    "OpportunityStatus",
    "Phase4Status",
    "Phase2Status",
    "REQUIRED_BAR_STARTS",
    "RiskOverlayResult",
    "RiskStatus",
    "PortfolioAllocationResult",
    "PositionLot",
    "PositionState",
    "PositionStatus",
    "PositionTransitionResult",
    "SHANGHAI_TIMEZONE",
    "SecurityStatus",
    "TradingRuleSnapshot",
    "SizingResult",
    "T1RiskObservation",
    "T1RiskResult",
    "TransitionStatus",
    "abs_rs",
    "calculate_opportunity_scores",
    "calculate_candidate_sizing",
    "calculate_divergence",
    "calculate_emergency_market_gate",
    "calculate_execution_gate",
    "calculate_fill_fees",
    "calculate_macd",
    "calculate_market_overlay",
    "calculate_risk_overlay",
    "calculate_t1_risk",
    "calculate_weighted_benchmark_returns",
    "clip01",
    "effective_exposure_cap",
    "empty_position_state",
    "execute_fill",
    "allocate_portfolio",
    "apply_buy_fill",
    "apply_sell_fill",
    "build_t1_risk_observation",
    "correlation_multiplier_for_candidate",
    "find_swing_points",
    "legal_bar_start_times",
    "linear_quantile_95",
    "normal_and_effective_risk",
    "normalize_security_symbol",
    "resolve_next_execution_bar",
    "order_quantity",
    "pearson_correlation",
    "raw_weight_from_risk",
    "score_close_ma20",
    "score_ma20_ma60",
    "score_ma60_slope",
    "score_signed_er",
    "score_signed_er_change",
    "score_index_factors",
    "signed_er_series",
    "validate_minute_bars",
    "validate_target_minute_bars",
    "unlock_position_state",
    "wilder_atr",
    "COOLDOWN_DAYS",
    "AttemptIdentity",
    "CooldownRecord",
    "CooldownStatus",
    "DeriskHoldingInput",
    "EXIT_PRIORITY",
    "ExitControlState",
    "ExitCycleHoldingInput",
    "ExitCycleResult",
    "ExitDecisionResult",
    "ExitDecisionStatus",
    "ExitIntent",
    "PendingSellState",
    "PendingSellStatus",
    "PendingUpdateResult",
    "PortfolioDeriskResult",
    "ReplacementCandidate",
    "ReplacementIncumbent",
    "ReplacementResult",
    "StopUpdateResult",
    "apply_pending_fill_result",
    "build_exit_fill_request",
    "canonical_exit_priority",
    "cooldown_blocked",
    "create_cooldown_record",
    "create_or_merge_pending",
    "coordinate_1430_exit_cycle",
    "initial_pending_attempt",
    "evaluate_1430_exit",
    "evaluate_hard_exit",
    "in_soft_exit_protection",
    "initialize_exit_control",
    "mark_episode_acted",
    "merge_cooldown_records",
    "next_pending_attempt",
    "plan_portfolio_derisk",
    "record_full_exit",
    "reduction_quantity",
    "revalidate_pending",
    "select_highest_intent",
    "select_replacement_exit",
    "update_trailing_stop",
    "AccountProfile",
    "AccountSnapshot",
    "BENCHMARK_SYMBOLS",
    "CachePartition",
    "CoreStrategyDependencies",
    "RuntimeDataDependencies",
    "ClockEvent",
    "DataCatalog",
    "DataReadinessReport",
    "DataSnapshot",
    "DateRangeKind",
    "DateRangeSpec",
    "LedgerEvent",
    "LookaheadAccessError",
    "MarketCache",
    "MarketView",
    "NetworkAccessPolicy",
    "PartitionRequest",
    "PartitionStatus",
    "PerformanceMetrics",
    "Phase5Error",
    "Phase5Service",
    "RAW_PRICE_BASIS",
    "ResolvedDateRange",
    "ResolvedUniverse",
    "RunConfig",
    "RunMode",
    "RunStatus",
    "RunStore",
    "RunSummary",
    "RuntimeHooks",
    "ServiceResult",
    "SessionCloseMark",
    "UniverseKind",
    "UniverseSnapshot",
    "UniverseSpec",
    "WARMUP_TRADING_DAYS",
    "apply_fill_to_ledger",
    "build_benchmark_curve",
    "build_event_clock",
    "calculate_performance_metrics",
    "create_account_snapshot",
    "create_data_snapshot",
    "create_run",
    "deterministic_id",
    "execute_run",
    "fetch_complete_partition",
    "generate_run_report",
    "prepare_market_cache",
    "rebuild_cash",
    "resolve_date_range",
    "resolve_run_inputs",
    "resolve_universe",
    "resume_run",
    "run_fingerprint",
    "validate_data_readiness",
    "validate_coverage",
    "select_session_close_mark",
    "validate_partition",
    "verify_data_snapshot",
]
